### ISSUE TITLE
Opening Classroom Early 9/7/21

### ISSUE THREAD

**Issue by epiechow** [CMU-MS-DAS-Modern-Programming-Mini/Syllabus#3]
Hello Sean,

Would it be possible to have the classroom opened early tomorrow, 9/7, so we can do our remote learning for Professor Olexandr's lecture? The lecture begins at 10:10AM and ends at 11:30. Apologies for the late message and thank you!

**Comment by shots47s** [comment]
Hi,

First off, the correct spelling of my name is "Shawn"

I am not going to be here at that time, But I have someone unlocking the
door for you.

Cheers,
Shawn
